include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # هنا نخبر المحلل بتجاهل هذه التنبيهات تمامًا
    unused_import: ignore
    deprecated_member_use: ignore
    avoid_print: ignore
    use_build_context_synchronously: ignore

linter:
  rules:
    # هنا نوقف قواعد المدقق (التي تعتبر rules)
    avoid_print: false
    use_build_context_synchronously: false