// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcZqc8K1lO1fUhLH67lYt1XGK1zq81maY',
    appId: '1:700829886116:web:67e0c13bd32a6442602831',
    messagingSenderId: '700829886116',
    projectId: 'velin-app-notifications',
    authDomain: 'velin-app-notifications.firebaseapp.com',
    storageBucket: 'velin-app-notifications.firebasestorage.app',
    measurementId: 'G-34B4GMK24D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBycpS7GELTEQRBqofx-lHTTKxKeeWl3qM',
    appId: '1:700829886116:android:caa479ce6c62dd92602831',
    messagingSenderId: '700829886116',
    projectId: 'velin-app-notifications',
    storageBucket: 'velin-app-notifications.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwTo4nvbvVa8haWE8ywDCA9Ph5llFBvt4',
    appId: '1:700829886116:ios:28be74494c3d3cc5602831',
    messagingSenderId: '700829886116',
    projectId: 'velin-app-notifications',
    storageBucket: 'velin-app-notifications.firebasestorage.app',
    iosBundleId: 'com.example.myapprun',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwTo4nvbvVa8haWE8ywDCA9Ph5llFBvt4',
    appId: '1:700829886116:ios:28be74494c3d3cc5602831',
    messagingSenderId: '700829886116',
    projectId: 'velin-app-notifications',
    storageBucket: 'velin-app-notifications.firebasestorage.app',
    iosBundleId: 'com.example.myapprun',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcZqc8K1lO1fUhLH67lYt1XGK1zq81maY',
    appId: '1:700829886116:web:18015dbece2a073e602831',
    messagingSenderId: '700829886116',
    projectId: 'velin-app-notifications',
    authDomain: 'velin-app-notifications.firebaseapp.com',
    storageBucket: 'velin-app-notifications.firebasestorage.app',
    measurementId: 'G-PNTXJ2BLCX',
  );
}
